version: '3.5'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres

# Create a service named postgresql.
  postgres:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    build: .
#   Give the container name sort_music. You can change it to something else, if you realy need it.
    container_name: "sort_music"
#   Setup the username, password and database name. You can change this values.
    environment:
      - POSTGRES_USER=sorter
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=musicDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
#   Maps port 1234 (localhost) to port 5432 on the container. You can change the posts to fix your needs.
    # maybe we can use this one "5432:5432" ?
    ports:
      - "5432:5432"
#   Set a volume so that data is not lost after shutting down the container.
#   I used name postgres-data but you can change it to something else.
    restart: unless-stopped


volumes:
  postgres-data: